import type { Fixture } from "./types";
export const fixtures: Fixture[] = [
 {id:"stripe",title:"Should we migrate payments to Stripe?",description:"Internal memo · 6 claims · mixed confidence",mode:"vendor",text:"Team — Stripe would let us ship payments faster and cut our maintenance burden. Their processing fees are lower than our current blended rate, and Stripe Billing will handle our usage-based pricing without custom work. Stripe is also the safest option because every comparable startup has moved there. Migration should take two weeks with no meaningful revenue risk.",claims:[
  {id:"c1",text:"Stripe would let us ship payments faster and reduce maintenance burden.",type:"causal",importance:"high",grade:"solid",confidence:.86,rationale:"The platform has broad primitives and mature documentation, though integration effort depends on your existing ledger and tax stack.",sources:["Stripe docs","SaaSFrame benchmark"]},
  {id:"c2",text:"Stripe’s processing fees are lower than our current blended rate.",type:"quantitative",importance:"high",grade:"shaky",confidence:.58,rationale:"List pricing is easy to compare, but blended rates depend on geography, volume, disputes, and negotiated pricing.",sources:["Stripe pricing","Internal memo"]},
  {id:"c3",text:"Stripe Billing handles usage-based pricing without custom work.",type:"comparative",importance:"high",grade:"contested",confidence:.72,rationale:"Usage meters exist, but teams still report custom entitlement, invoicing, and reconciliation work around the edges.",sources:["Stripe Billing docs","Capterra review"]},
  {id:"c4",text:"Every comparable startup has moved to Stripe.",type:"comparative",importance:"medium",grade:"contested",confidence:.91,rationale:"The claim is too broad. Stripe is common, but public examples show meaningful use of Adyen, Braintree, and in-house systems.",sources:["Stripe customer list","Adyen case studies"]},
  {id:"c5",text:"Migration will take two weeks with no meaningful revenue risk.",type:"quantitative",importance:"high",grade:"unknown",confidence:.34,rationale:"No architecture, volume, payment-method, or rollback details support this estimate. Treat it as a planning hypothesis.",sources:["Internal memo"]}
 ],brief:{bottomLine:"Stripe looks like a credible default, but this memo is selling certainty it hasn’t earned. The product fit is real; the fee savings and two-week migration are not yet decision-grade.",trust:"The platform breadth and mature payment primitives are well supported. Stripe can plausibly reduce owned maintenance for a small team.",contested:"Billing effort, fee savings, and the ‘everyone moved’ comparison are all more nuanced than the memo suggests.",risks:"A rushed migration can create payment-method gaps, reconciliation drift, or an expensive rollback during a revenue-critical window.",next:"Model fees against 90 days of actual transactions, map custom billing workflows, and run a thin-slice migration with a rollback plan."}},
 {id:"strategy",title:"Fact-check this AI strategy answer",description:"AI-generated advice · 4 claims · overconfident",mode:"factcheck",text:"AI answer: The best AI companies all train their own foundation models. RAG eliminates hallucinations when it uses a vector database. OpenAI’s API data is always used to train models unless you opt out. Adding more agents always improves answer quality.",claims:[
  {id:"c1",text:"The best AI companies all train their own foundation models.",type:"comparative",importance:"high",grade:"contested",confidence:.94,rationale:"Leading companies use a mix of proprietary models, fine-tuning, and hosted frontier models. ‘All’ is directly contradicted by public practice.",sources:["OpenAI API docs","Anthropic case study"]},
  {id:"c2",text:"RAG eliminates hallucinations when it uses a vector database.",type:"causal",importance:"high",grade:"contested",confidence:.97,rationale:"Retrieval can ground answers, but bad retrieval, synthesis errors, and missing evidence still produce hallucinations.",sources:["Stanford RAG survey","Google Cloud guide"]},
  {id:"c3",text:"OpenAI API data is always used to train models unless you opt out.",type:"factual",importance:"high",grade:"solid",confidence:.98,rationale:"For the API, data is not used to train models by default; product-specific retention and abuse-monitoring terms still matter.",sources:["OpenAI API docs","OpenAI privacy"]},
  {id:"c4",text:"Adding more agents always improves answer quality.",type:"causal",importance:"medium",grade:"unknown",confidence:.86,rationale:"More agents can improve coverage, but coordination cost, duplicated work, and error propagation make ‘always’ indefensible.",sources:["Microsoft AutoGen research"]}
 ],brief:{bottomLine:"This answer has a real fact buried inside a lot of absolutist language. Treat it as a useful list of hypotheses, not an architecture recommendation.",trust:"The API training-data claim checks out in the stated default. Multi-agent systems can help when roles are bounded and outputs are reduced.",contested:"Model ownership and RAG’s effect on hallucinations are both overstated. The ‘always’ claims should be removed before sharing this.",risks:"Repeating these claims can push a team toward expensive model training or agent complexity before the simpler retrieval and evaluation work is done.",next:"Rewrite around measurable quality targets: citation coverage, grounded accuracy, latency, and cost per successful task."}},
 {id:"event-driven",title:"Competitor all moved to event-driven architecture",description:"Slack dump + blog summaries · 5 claims · loud opinions",mode:"strategy",text:"Slack #eng: Maya: Everyone in our space is going event-driven now. Leo: The Acme blog says their deploy frequency doubled after the move. Priya: This means synchronous APIs are basically obsolete. Summary bot: Event-driven systems are cheaper, more scalable, and always more resilient. We should follow before we fall behind.",claims:[
  {id:"c1",text:"Every competitor in our space is moving to event-driven architecture.",type:"comparative",importance:"high",grade:"contested",confidence:.89,rationale:"The sample is two anecdotes and a bot summary, not a market census. Adoption is real but uneven and definition-dependent.",sources:["Acme engineering blog","Slack excerpt"]},
  {id:"c2",text:"Acme doubled deploy frequency after the move.",type:"quantitative",importance:"medium",grade:"shaky",confidence:.61,rationale:"Acme reports the change, but the post does not isolate architecture as the cause or provide a comparable baseline.",sources:["Acme engineering blog"]},
  {id:"c3",text:"Synchronous APIs are basically obsolete.",type:"factual",importance:"high",grade:"contested",confidence:.93,rationale:"Event-driven and synchronous patterns commonly coexist. Request/response remains useful for user-facing reads and tightly coupled operations.",sources:["AWS architecture center","Martin Fowler"]},
  {id:"c4",text:"Event-driven systems are always cheaper and more resilient.",type:"causal",importance:"high",grade:"unknown",confidence:.9,rationale:"There are real scaling and decoupling benefits, but operations, observability, delivery semantics, and debugging add cost and failure modes.",sources:["AWS architecture center"]}
 ],brief:{bottomLine:"There is a pattern worth investigating, not a race we’re losing. The evidence supports event-driven architecture as a tool, not a universal replacement for synchronous APIs.",trust:"Event-driven systems can decouple producers and consumers and help with certain scale and availability needs.",contested:"The competitor sweep, causal link to deploy frequency, and ‘obsolete’ framing all rely on thin or self-reported evidence.",risks:"Following the trend without a bounded use case could buy a distributed-systems tax without improving the customer path.",next:"Pick one async workflow with measurable pain, define success metrics, and compare it with a simpler queue or modular monolith option."}}
];
